### ISSUE TITLE
Sign a transaction

### ISSUE THREAD

**Issue by hauleth** [eigerco/uniffi-zcash-lib#34]

**Comment by eloylp** [comment]
In #31 we implemented 2 Transaction builders, one for `Orchard` and the other one for `Sapling` and `Transparent`. In such builders, we can add the relevant inputs/outputs and then we **build and sign** the transaction in one step, ready to be sent to the network.

Does the above mean this issue is superseded by #31 ? maybe not. Another possibility, is that we should be able to parse a Transaction from a buffer, by using the outcome of #32 and #33, and then sign it if needed. If that the case, we probably should investigate how to abstract the signing/proving logic from the respective commented builders.
