### ISSUE TITLE
Explore the internal structure of a transaction (using structs or the equivalent in the given language)

### ISSUE THREAD

**Issue by hauleth** [eigerco/uniffi-zcash-lib#36]

**Comment by eloylp** [comment]
I am investigating what could be the interested parts to expose.  I think there are 2 possible entities involved here. The [Transaction](https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L281)  and the [TransactionData](https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L301) one. The former its more about serialization methods of the whole transaction and contains the latter. The latter has access to the internal parts of the transaction. Here is a non exhaustive list of methods to implement from them:

* https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L366-L382
* https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L390-L394
* https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L406
* https://github.com/zcash/librustzcash/blob/main/zcash_primitives/src/transaction/mod.rs#L559

In the above listing, for `TransactionData`, the methods `transparent_bundle()` , `sapling_bundle()` and `orchard_bundle()` provides access to their respective inputs/outputs. That would involve mapping also the bundle types at least, at a basic level.

**Comment by eloylp** [comment]
Allright ! i will take care of this. Lets start exposing the commented methods/types and explore a bit more the code.

**Comment by eloylp** [comment]
There is a decision about API design that i am thinking about. Mozilla UniFFI  [enums](https://mozilla.github.io/uniffi-rs/udl/enumerations.html) representation does not support having methods associated. For the case of [TxVersion](https://docs.rs/zcash_primitives/0.11.0/zcash_primitives/transaction/enum.TxVersion.html) , we need to access the implemented methods to get a description of the internal parts of the transaction.

How i am currently solving it ? Well, it passes through a bit of a convention. It consist in defining a struct `ZcashTxVersion` that wraps the original enum, rather than representing it with another enum (1:1). Inside that struct, there is a pure invention method called `selection()` , that would return the specific, current variant of the inner enumeration:

```c++
[Enum]
interface ZcashTxVersionSelection {
    Sprout(u32 v);
    Overwinter();
    Sapling();
    Zip225();
};

interface ZcashTxVersion {
    ZcashTxVersionSelection selection();
   // More methods that retrieve transaction data goes here ...
}
```
So, we can somehow preserve the data together with the enum. This works for the case of retrieving the data from the transaction. In the opposite case of providing the enum `ZcashTxVersionSelection` , the `From` traits would do the conversion, from `ZcashTxVersionSelection` to `TxVersion`.

If using this its not too annoying , probably i would go for it. Lets see how it plays overall ! If you agree and plays well, i would probably add this to our wiki "conventions" section.

cc: @MeerKatDev @zduny

**Comment by eloylp** [comment]
Okay, i think we covered more or less the [commented](https://github.com/eigerco/uniffi-zcash-lib/issues/36#issuecomment-1507079340) surface and downstream dependencies.

Moving to review #112 ! @MeerKatDev @zduny :fast_forward: 

In the meanwhile, i will be writing some python tests.

**Comment by eloylp** [comment]
The python tests for demonstrating we can explore the different parts of a transaction are on this [PR](https://github.com/eigerco/uniffi-zcash-lib/pull/114) . Moving this for review again.

There are BTW some extra crypto functions in the `Orchard` bundle i am trying to include in another tests in the meanwhile.

**Comment by eloylp** [comment]
Okay, looks like the functionality is implemented now.

The testing of the [commented](https://github.com/eigerco/uniffi-zcash-lib/issues/36#issuecomment-1519619044) crypto functions are going to be addresed on #117 . Closing this.
